# Generated by Django 3.1.4 on 2021-05-21 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20210521_0530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='material',
            name='slug',
        ),
    ]
